name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Install build dependencies
      run: |
          apt-get update
          apt-get install -y pkg-config build-essential xorg-dev

    - name: Build
      run: go build -o vanilla-tools/ ./...
    
    - name: Compress
      run: tar -czvf vanilla-tools.tar.gz vanilla-tools/*
    
    - name: Calculate and Save Checksums
      run: |
        sha256sum vanilla-tools.tar.gz >> checksums.txt

    - uses: actions/upload-artifact@v4
      with:
        name: vanilla-tools
        path: |
          checksums.txt
          vanilla-tools.tar.gz

    - name: Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: |
          checksums.txt
          vanilla-tools.tar.gz
