name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

  upload-artifacts:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
     - uses: actions/checkout@v4

     - name: Set up Go
       uses: actions/setup-go@v4
       with:
         go-version: 1.19
    
     - name: Install build dependencies
       run: |
           apt-get update
           apt-get install -y pkg-config build-essential xorg-dev
    
     - name: Build
       run: go build -o vanilla-tools/ ./...
        
     - name: Compress
       run: tar -czvf vanilla-tools.tar.gz vanilla-tools/*

     - uses: softprops/action-gh-release@v1
       with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            vanilla-tools.tar.gz
